apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-deployment
  labels:
    app: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
      - name: activemq
        image: rmohr/activemq
        ports:
        - containerPort: 8161
        - containerPort: 1883
        volumeMounts:
        - name: env-volume
          mountPath: /opt/activemq/bin/env
          subPath: env
        - name: prom-config-volume
          mountPath: /opt/activemq/bin/prom-comfig.yaml
          subPath: prom-config.yaml
        command: ["java"]
        args: ["-javaagent:./jmx_prometheus_javaagent-0.19.0.jar=<11099>:/opt/activemq/bin/prom-config.yaml", "-jar", "/opt/activemq/bin/prom-activemq.jar"]
        resources:
          limits:
            memory: 1024Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.5"
      volumes:
        - name: env-volume
          configMap:
            name: env-config
        - name: prom-config-volume
          configMap:
            name: prom-config-config
---
apiVersion: v1
kind: Service
metadata:
  name: activemq-hmi-service
spec:
  selector:
    app: activemq
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: activemq-hmi
    port: 8161
    targetPort: 8161
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: activemq-service
spec:
  selector:
    app: activemq
  ports:
  - protocol: TCP
    name: activemq
    port: 1883
    targetPort: 1883


